client:
	sudo gcc simDNSClient.c -o simDNSClient
	sudo ./simDNSClient ca:63:21:22:f0:88 192.168.64.4 ca:63:21:22:f0:88 192.168.64.4
server:
	sudo gcc simDNSServer.c -o simDNSServer
	sudo ./simDNSServer ca:63:21:22:f0:88 192.168.64.4
clean:
	sudo rm simDNSClient simDNSServer
